// <auto-generated />
namespace CIS467_AMP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRequestStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRequestStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201702281724041_AddRequestStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
