// <auto-generated />
namespace CIS467_AMP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddShared6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddShared6));
        
        string IMigrationMetadata.Id
        {
            get { return "201703120618053_AddShared6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
